import { TextureSource, ExtensionType, extensions } from "pixi.js"
import type { GlTexture, GLTextureUploader } from "pixi.js"

/** The six face textures of one mip level. */
export interface CubemapFaceSources {
  posx: TextureSource
  negx: TextureSource
  posy: TextureSource
  negy: TextureSource
  posz: TextureSource
  negz: TextureSource
}

/**
 * Face order matching the WebGL cube map targets, so face `i` uploads to
 * `TEXTURE_CUBE_MAP_POSITIVE_X + i`.
 */
const FACE_ORDER: (keyof CubemapFaceSources)[] = [
  "posx", "negx", "posy", "negy", "posz", "negz"
]

const UPLOAD_METHOD_ID = "cubemap"

/**
 * Texture source for a cube map whose mip levels are supplied by the user,
 * one set of six faces per level, rather than generated by the GPU. This is
 * what pre-filtered environment maps for image-based lighting need: each
 * level holds a different roughness, so `generateMipmap` would be wrong.
 *
 * PixiJS v8 has native cube textures (`viewDimension: "cube"`), but its own
 * cube uploader only uploads level 0 of each face. This source declares its
 * own upload method, registered below, which uploads every level of every
 * face and leaves mipmap generation off.
 */
export class CubemapResource extends TextureSource<CubemapFaceSources[]> {
  /**
   * Creates a new cubemap resource from the specified mip levels. Level 0 is
   * the largest; every following level halves the size.
   * @param mipmaps The faces for each mip level.
   */
  constructor(mipmaps: CubemapFaceSources[]) {
    if (mipmaps.length === 0) {
      throw new Error("PIXI3D: A cubemap needs at least one mip level.")
    }
    const base = mipmaps[0].posx
    super({
      resource: mipmaps,
      width: base.width,
      height: base.height,
      resolution: base.resolution,
      format: base.format,
      dimensions: "2d",
      viewDimension: "cube",
      arrayLayerCount: 6,
      mipLevelCount: mipmaps.length,
      autoGenerateMipmaps: false,
      // The faces are data (environment radiance, RGBE exponents in the
      // alpha channel); premultiplying them on upload would corrupt them.
      alphaMode: "no-premultiply-alpha",
      addressMode: "clamp-to-edge",
      scaleMode: "linear",
      label: "cubemap",
    })
    this.uploadMethodId = UPLOAD_METHOD_ID
    for (const face of FACE_ORDER) {
      mipmaps[0][face].on("resize", this._onFaceResize, this)
      mipmaps[0][face].on("update", this._onFaceUpdate, this)
    }
  }

  /** The mip levels, each holding six faces. */
  get mipmaps() {
    return this.resource
  }

  /** The number of mip levels. */
  get levels() {
    return this.mipLevelCount
  }

  /**
   * Value indicating if every face of every level has loaded, i.e. has a
   * resource with a non-zero size. Faces created from images that are still
   * decoding report a 0x0 size until they finish.
   */
  get valid() {
    return this.resource.every(level => FACE_ORDER.every(face => {
      const source = level[face]
      return !!source.resource && source.pixelWidth > 0 && source.pixelHeight > 0
    }))
  }

  private _onFaceResize() {
    const base = this.resource[0].posx
    this.resize(base.width, base.height, base.resolution)
  }

  private _onFaceUpdate() {
    this.update()
  }

  destroy() {
    const mipmaps = this.resource
    if (mipmaps) {
      for (const face of FACE_ORDER) {
        mipmaps[0][face].off("resize", this._onFaceResize, this)
        mipmaps[0][face].off("update", this._onFaceUpdate, this)
      }
    }
    super.destroy()
  }
}

/**
 * Uploads every level of every face. Registered as a WebGL texture uploader
 * extension, which the texture system copies into its uploader table by
 * `uploadMethodId` when it is constructed, so this module must be imported
 * before the renderer is created (the same rule as for every other pixi3d
 * extension).
 */
const cubemapUploader: GLTextureUploader & { extension: unknown } = {
  extension: { type: ExtensionType.TextureUploaderWebGL, name: UPLOAD_METHOD_ID },
  id: UPLOAD_METHOD_ID,
  upload(source: TextureSource, glTexture: GlTexture, gl: WebGLRenderingContext | WebGL2RenderingContext) {
    const mipmaps = (<CubemapResource>source).mipmaps
    for (let level = 0; level < mipmaps.length; level++) {
      for (let i = 0; i < FACE_ORDER.length; i++) {
        const face = mipmaps[level][FACE_ORDER[i]]
        const target = gl.TEXTURE_CUBE_MAP_POSITIVE_X + i
        let data = face.resource
        if (!data) {
          continue
        }
        if (data instanceof ArrayBuffer) {
          data = new Uint8Array(data)
        }
        if (ArrayBuffer.isView(data)) {
          gl.texImage2D(target, level, glTexture.internalFormat, face.pixelWidth,
            face.pixelHeight, 0, glTexture.format, glTexture.type, <ArrayBufferView>data)
        } else {
          gl.texImage2D(target, level, glTexture.internalFormat,
            glTexture.format, glTexture.type, <TexImageSource>data)
        }
      }
    }
    glTexture.width = source.pixelWidth
    glTexture.height = source.pixelHeight
  }
}

extensions.add(cubemapUploader)
